# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bb39ec670ae9a0016fa42da5d3ba74eb79d705d89b7c4c1b5893afe4f59c2e8edd32681f5bf95ed914a8506bdc42aa3aab6fc065f967bac5b0fda46900a3402

test:
  secret_key_base: 0433f057e575edf29ca27bf41d465bd2ed23f1619995519ad346c85a3b7115be3bbd7713ad0cfa62bea696107e6171ee96a4e7767cc8e1d0d689e2cf669a6cf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
